### ISSUE TITLE
Repo looks interesting but eyes hurt at the page!

### ISSUE THREAD

**Issue by iRupam** [visualize-it/visualize-it.github.io#1]
@chanrt The background of checker pattern really doesn't go well. It would be better if the background is changed to something where eyes don't hurt!
I checked out the Nuclear fusion [page](https://visualize-it.github.io/nuclear_fusion/simulation.html). I tried with 500000 nuclei and after clicking on Restart, the page completely freezes.
It's a good project though, will try to go through all of projects in the website and try to make it better!

**Comment by chanrt** [comment]
> The background of checker pattern really doesn't go well. It would be better if the background is changed to something where eyes don't hurt!

![image](https://github.com/visualize-it/visualize-it.github.io/assets/61446958/d02a16b5-95f1-44a8-a387-c21e81d77ca6)

When you open the page, do you see something similar to what I've linked above?

What exactly is wrong with the background pattern? Does it make the text unreadable? Is the contrast too high?

Please let me know

**Comment by chanrt** [comment]
> I tried with 500000 nuclei and after clicking on Restart, the page completely freezes.

The number of interactions between nuclei scale as O(N^2) so it is a bad idea to simulate 500000 nuclei. JavaScript wasn't made to handle simulations in the first place ;-)

**Comment by chanrt** [comment]
> It's a good project though, will try to go through all of projects in the website and try to make it better!

Thanks! I have never had people give me detailed feedback before so it will certainly help.

Please create separate issue for each problem you face.

**Comment by iRupam** [comment]
Thanks @chanrt. Will try to go through the whole project by this weekend. Hopefully, I can improve the repository and provide some useful feedback to you regarding the same.
